### ISSUE TITLE
[Enhancement] Allow instance admins enable sharing of their instance without accepting new communities

### ISSUE THREAD

**Issue by DraconicNEO** [ismailkarsli/lemmy-federate#16]
I think there should be an option to allow instance admins to allow for the communities on their server to be shared with other instances via lemmy-federate but without communities from other instances being pulled into their own instance. This is mainly because pulling in communities from other servers creates increased storage demand more so than sharing their own communities would. It's a good compromise that allows storage conscious admins to use the tool to share their own communities without burdening their own instance as much.

Under this new option
```
Local communities ------> Remote instances
```
But
```
Local instance           X<----- Remote communities
```

I hope I got the general idea across.

**Comment by DraconicNEO** [comment]
Feel free to change the title to something better, I'm tired and have been running on coffee all day so I might not have had the best idea for wording it.

**Comment by ismailkarsli** [comment]
I'm currently refactoring the codebase. I may add this feature in the future. I have 3 modes in mind: "full", "seed", "leech".

**Comment by ismailkarsli** [comment]
I just added this option as “federation mode” along with Mbin support. I’m gonna announce it tomorrow hopefully.

**Comment by DraconicNEO** [comment]
> I just added this option as “federation mode” along with Mbin support. I’m gonna announce it tomorrow hopefully.

Is there a place to subscribe to so I'll find out when it happens (assuming it didn't already, I didn't see any change in the site since I am not an admin of an instance that uses it).

**Comment by ismailkarsli** [comment]
@DraconicNEO It’s done 🙂 https://lemmy.world/post/21212938
