### ISSUE TITLE
[Big] Certain Lemmy instances seem not allowed for no reason

### ISSUE THREAD

**Issue by DraconicNEO** [ismailkarsli/lemmy-federate#20]
I've been adding communities and I noticed that for some reason some Lemmy instances are displaying "Not allowed" despite being federated with the instance and the community not being NSFW in nature. Any idea what's going on? I tried to add !stable_dragons@lemmy.dbzer0.com and recently !privacy@lemmy.dbzer0.com and both seem to not be allowed by lemmy.world. I checked and was able to search for them on Lemmy.world so I don't think federation is the issue here.

**Comment by ismailkarsli** [comment]
Here’s the admin page:

![IMG_1778](https://github.com/user-attachments/assets/0d7201e9-abf4-48ed-a3d5-f24f60da4bf6)

So there are other filters too. Also lemmy.world using explicit allow list as far as I know.

**Comment by DraconicNEO** [comment]
Ah I see. I thought it might've been a bug of some kind. I'll ask them about why it might be happening.
