### ISSUE TITLE
Does not recognize an admin user as such.

### ISSUE THREAD

**Issue by FatherMcGruder** [ismailkarsli/lemmy-federate#21]
Trying to log into lemmy-federate with user CrimeDad and instance lemmy.crimedad.work,but I get an error that that user isn't an admin. However, it certainly is the admin account of that instance according to [the red A on its profile page](https://lemmy.crimedad.work/u/CrimeDad).

Could there be something about that instance or account that's causing the problem?

**Comment by ismailkarsli** [comment]
My guess is that the version of the instance is outdated. It’s 1.5 years old version.

Can you at least update to 0.19.0?

**Comment by FatherMcGruder** [comment]
Unfortunately, no. I'm running the Yunohost Lemmy package, which is behind. Apparently, it is held up because Yunohost was based on an older version of Debian, but it has recently updated to Bookworm, so Lemmy 0.19 shouldn't be far off.
--

**Comment by ismailkarsli** [comment]
The login issue should be fixed with https://github.com/ismailkarsli/lemmy-federate/commit/e1492609cbda729a92ba3e45f26cb84fba61bc05.

**Comment by FatherMcGruder** [comment]
> The login issue should be fixed with [e149260](https://github.com/ismailkarsli/lemmy-federate/commit/e1492609cbda729a92ba3e45f26cb84fba61bc05).

Okay, I was able to log in successfully. Thanks!
